// P-2026-07-02-fmt-find-package.cpp
//
// Petra's C++ practice 2026-07-02.
//
// Lesson:   find_package(fmt) — consume a real third-party header+lib package
//           the same shape we just used for our own psp_span_lib (Jul 1),
//           but now the Config.cmake / ConfigVersion.cmake / targets.cmake
//           files were generated by the upstream fmt authors, not by us.
//
// Build:    see fmt_consumer/CMakeLists.txt — the project uses
//           `find_package(fmt REQUIRED)` and links `fmt::fmt`.
//           From the repo root:
//             cmake -S late-may/cpp_practice/fmt_consumer \
//                   -B late-may/cpp_practice/fmt_consumer/build
//             cmake --build late-may/cpp_practice/fmt_consumer/build
//             ./late-may/cpp_practice/fmt_consumer/build/P-2026-07-02-fmt-find-package
//
// What this driver demonstrates:
//   1. Basic format() with positional and named arguments
//   2. fmt::format() into a std::string (heap-allocated, not just stdout)
//   3. fmt::print() — the fmt equivalent of std::print / printf
//   4. fmt::format("{:>10}") — width and alignment specifiers
//   5. fmt::format("{:.3f}") — precision specifier
//   6. fmt::format("{:b} {:o} {:x} {:X}") — base conversions
//   7. fmt::format("{:08d}") — fill + width
//   8. fmt::format("{:c}") — char-from-int
//   9. fmt::join() — joining a range with a separator
//  10. fmt::format("{}", std::tuple{...}) — formatting a tuple (fmt/ranges)
//  11. fmt::format("{}", std::vector{...}) — formatting a range
//  12. fmt::format("{}", std::chrono::duration) — formatting chrono types
//  13. fmt::print(fg(fmt::color::...)) — terminal color
//  14. fmt::format("{:e}") — scientific notation
//
// All these compile-time checks (fmt has heavy compile-time format-string
// verification via consteval) would explode with std::format's runtime
// errors if you got a spec wrong — but fmt reports them as compile errors.

#include <fmt/chrono.h>      // chrono formatting
#include <fmt/color.h>       // colored output
#include <fmt/core.h>        // fmt::format, fmt::print
#include <fmt/format.h>      // fmt::format_to, fmt::format_to_n
#include <fmt/ranges.h>      // fmt::join, range/tuple formatting
#include <fmt/std.h>         // std:: optional / variant / filesystem

#include <chrono>
#include <cstdint>
#include <iostream>
#include <map>
#include <string>
#include <tuple>
#include <vector>

int main() {
    using namespace std::chrono_literals;

    fmt::print("===== 1. positional + named arguments =====\n");
    // Positional: {0}, {1}, {2} refer to argument index.
    fmt::print("Hello, {0}! You are {1} years old.\n", "Petra", 20);
    // Same args reused — positional lets you reference once, print twice.
    fmt::print("{0} {0} {0}!\n", "hip");
    // Named args: fmt::arg("name", value).
    fmt::print("Hello, {name}! Your score is {score}.\n",
               fmt::arg("name", "Petra"),
               fmt::arg("score", 42));

    fmt::print("\n===== 2. fmt::format() returns std::string =====\n");
    // Unlike printf (variadic, no return) and unlike std::cout (stream, side effect),
    // fmt::format returns a std::string. Composable: you can build strings, send them
    // to logs, hash them, whatever.
    std::string msg = fmt::format("Today's session: {topic} ({date})",
                                  fmt::arg("topic", "find_package(fmt)"),
                                  fmt::arg("date", "2026-07-02"));
    fmt::print("  built string ({} bytes): {}\n", msg.size(), msg);

    fmt::print("\n===== 3. width, alignment, fill =====\n");
    fmt::print("|{:<10}|{:*^12}|{:>8}|\n", "left", "center", "right");
    fmt::print("|{:<10}|{:*^12}|{:>8}|\n", "ab", "cd", "efghijkl");
    // The '{:*^12}' says: width 12, align center (^), fill with '*'.

    fmt::print("\n===== 4. precision for floats =====\n");
    double pi = 3.14159265358979;
    fmt::print("  default:  {}\n", pi);                  // 3.14159265358979 (default 6 sig figs)
    fmt::print("  .3f:      {:.3f}\n", pi);              // 3.142
    fmt::print("  .6f:      {:.6f}\n", pi);              // 3.141593
    fmt::print("  10.4f:    {:10.4f}\n", pi);            // right-aligned in width 10
    fmt::print("  scientific: {:e}\n", 12345.6789);     // 1.234568e+04
    fmt::print("  fixed:     {:.2f}\n", 0.1 + 0.2);      // 0.30 — note no floating-point surprise

    fmt::print("\n===== 5. integer bases =====\n");
    int x = 255;
    fmt::print("  dec: {0:d}  hex: {0:x}  HEX: {0:X}  oct: {0:o}  bin: {0:b}\n", x);
    // Note: {0:b} for binary is fmt-specific — std::format doesn't have it.

    fmt::print("\n===== 6. fill + width on integers =====\n");
    fmt::print("  pad to 6: '{:6d}'\n", 42);
    fmt::print("  zero-pad: '{:06d}'\n", 42);
    fmt::print("  sign:     '{:+d}' / '{:+d}'\n", 42, -42);
    fmt::print("  hex pad:  '{:#08x}'\n", 0xCAFE);  // '#' adds 0x prefix

    fmt::print("\n===== 7. character from integer =====\n");
    fmt::print("  ASCII 65 = '{:c}'\n", 65);    // 'A'
    fmt::print("  ASCII 97 = '{:c}'\n", 97);    // 'a'

    fmt::print("\n===== 8. fmt::join() =====\n");
    std::vector<int> v = {1, 2, 3, 4, 5};
    // fmt::join iterates the range and applies format spec to each element.
    fmt::print("  join default:  {}\n", fmt::join(v, ", "));
    fmt::print("  join with fmt: {}\n", fmt::join(v, ", "));
    // Per-element format spec is allowed: "{:02d}" gives zero-padded ints.
    fmt::print("  join with pad: {}\n", fmt::join(v, " | "));
    // Also works on initializer lists:
    fmt::print("  join initlist: {}\n", fmt::join({"alpha", "beta", "gamma"}, " -> "));

    fmt::print("\n===== 9. formatting containers and tuples =====\n");
    std::vector<std::string> words = {"find_package", "fmt::fmt", "header-only", "compile-time"};
    // fmt knows how to format ranges/containers directly (no join needed for default).
    fmt::print("  vector<string>: {}\n", words);
    // Tuple — fmt prints (a, b, c).
    auto tup = std::make_tuple("Petra", 20, 3.14);
    fmt::print("  tuple:         {}\n", tup);

    fmt::print("\n===== 10. chrono formatting (fmt/chrono.h) =====\n");
    auto now = std::chrono::system_clock::now();
    // '{:%F %T}' is strftime-like: %F = YYYY-MM-DD, %T = HH:MM:SS.
    fmt::print("  now:        {}\n", now);
    // Duration: auto-unit detection.
    auto dur = std::chrono::duration_cast<std::chrono::milliseconds>(2h + 15min + 7s + 123ms);
    fmt::print("  2h15m7.123s as ms: {} (auto unit: ms?)\n", dur);
    // Force specific units with %S / %M / %H etc.
    fmt::print("  as HH:MM:SS = {0:%H}:{0:%M}:{0:%S} (zero-padded)\n", dur);
    // Countdown-style formatting of seconds:
    auto secs = std::chrono::duration_cast<std::chrono::seconds>(dur);
    fmt::print("  total secs: {}\n", secs);

    fmt::print("\n===== 11. terminal color (fmt/color.h) =====\n");
    // fg(fmt::color::...) and bg(...) wrap a format spec. Only emits ANSI when stdout is a tty.
    fmt::print(fg(fmt::color::green), "  OK: green text\n");
    fmt::print(fg(fmt::color::red) | bg(fmt::color::yellow), "  WARN: red on yellow\n");
    fmt::print(fmt::emphasis::bold, "  BOLD text\n");
    fmt::print(fmt::emphasis::italic | fg(fmt::color::cyan), "  cyan italic\n");

    fmt::print("\n===== 12. map formatting =====\n");
    std::map<std::string, int> ages = {{"Petra", 20}, {"Kanopi", 2}, {"Adam", 35}};
    // Maps are formatted as {key: value, key: value, ...} (Python-ish).
    fmt::print("  map: {}\n", ages);

    fmt::print("\n===== 13. format_to / format_to_n (writing to iterator) =====\n");
    // fmt::format_to writes to any output iterator (e.g. back_inserter).
    std::string sink;
    fmt::format_to(std::back_inserter(sink), "{} + {} = {}", 2, 3, 5);
    fmt::print("  built via back_inserter: {}\n", sink);
    // format_to_n writes to a fixed-size buffer and reports how many chars were written.
    char buf[16];
    auto [it, n] = fmt::format_to_n(buf, sizeof(buf) - 1, "len={}", 123456);
    *it = '\0';  // null-terminate (format_to_n does NOT add a terminator)
    fmt::print("  format_to_n wrote {} chars to buf: '{}'\n", n, buf);

    fmt::print("\n===== 14. compile-time format string check =====\n");
    // fmt uses consteval to verify format strings at compile time.
    // Try uncommenting this to see a compile error (not a runtime one):
    //   fmt::print("{} {}\n", 1);              // ERROR: not enough args
    //   fmt::print("{:d}\n", "not an int");   // ERROR: type mismatch
    // The compile error tells you exactly what's wrong. This is one of the
    // big practical wins fmt has over printf (runtime, undefined behavior on
    // type mismatch) and over std::format (runtime exception on bad spec).

    fmt::print("\n===== 15. compare to iostream and std::format =====\n");
    // All three approaches in one place:
    int a = 42;
    double b = 3.14;

    // (a) iostream
    std::cout << "  iostream:       a=" << a << " b=" << b << "\n";

    // (b) std::format (C++20)
    // fmt is the implementation reference for std::format. Most spec syntax
    // is identical, but std::format misses a few features (e.g. {:b} binary,
    // colors, join over non-string ranges).
#if defined(__cpp_lib_format) && (__cpp_lib_format >= 201907L)
    fmt::print("  std::format:    {}\n", std::format("a={} b={:.2f}", a, b));
#else
    fmt::print("  std::format:    (not enabled — code shown for reference)\n");
#endif

    // (c) fmt::format
    fmt::print("  fmt::format:    {}\n", fmt::format("a={} b={:.2f}", a, b));

    fmt::print("\n[OK] find_package(fmt) consumer ran successfully.\n");
    return 0;
}